### ISSUE TITLE
Logs incomplete

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/virtual-schema-common-java#227] opened 2021-06-10 13:02 UTC
When logging the virtual schema flow, the logs are incomplete, as it doesn't log the first `getCapabilities` request.

How to reproduce:

1) Install a virtual schema with a logger:
```
CREATE VIRTUAL SCHEMA <SCHEMA>
	USING <ADAPTER_SCRIPT> 
	WITH
	CATALOG_NAME = '<CATALOG>'
	SCHEMA_NAME = '<SCHEMA>'
	CONNECTION_NAME = '<CONNECTION>'
	DEBUG_ADDRESS='<IP_ADDRESS>:3000' LOG_LEVEL='ALL'
	;
```
2) On a terminal console, open `netcat` on listening mode:
`nc -lkp 3000`
3) Execute a select query on the virtual schema
`SELECT * FROM <VIRTUAL_SCHEMA>.<VIRTUAL_TABLE>`
4) Check the logs in the console, the `getCapabilities` request is not logged

Related issues: https://github.com/itsallcode/junit5-system-extensions/issues/20

**Comment by AnastasiiaSergienko** [comment] 2021-08-30 11:05
I cannot reproduce the issue. After executing the SELECT command I see the logs with getCapabilities:
```
2021-08-30 10:34:00.805 INFO    [c.e.l.RemoteLogManager] Attached to output service with log level ALL.
2021-08-30 10:34:00.816 FINE    [c.e.a.j.JDBCAdapter] Received request to list the adapter's capabilites.
2021-08-30 10:34:00.834 CONFIG  [c.e.a.j.JDBCAdapter] Excluded Capabilities: none
```

I'm closing the issue for now.

**Comment by chiaradiamarcelo** [comment] 2021-08-30 11:17
> I cannot reproduce the issue. After executing the SELECT command I see the logs with getCapabilities:
> 
> ```
> 2021-08-30 10:34:00.805 INFO    [c.e.l.RemoteLogManager] Attached to output service with log level ALL.
> 2021-08-30 10:34:00.816 FINE    [c.e.a.j.JDBCAdapter] Received request to list the adapter's capabilites.
> 2021-08-30 10:34:00.834 CONFIG  [c.e.a.j.JDBCAdapter] Excluded Capabilities: none
> ```
> 
> I'm closing the issue for now.

@AnastasiiaSergienko check for the `"Raw JSON request:\n"` message from the `RequestDispatcher` (https://github.com/exasol/virtual-schema-common-java/blob/main/src/main/java/com/exasol/adapter/RequestDispatcher.java#L57) when the `getCapabilities` request is triggered. The log you are seeing there is from the `JDBCAdapter` implementation, not from the `RequestDispatcher`.

**Comment by AnastasiiaSergienko** [comment] 2021-08-30 11:39
Hello @chiaradiamarcelo ! Thanks for the comment, I'll check this.

**Closed** 2022-01-05 08:44 UTC
Labels: bug, source:exasol
