### ISSUE TITLE
Inconsistent data types

### ISSUE THREAD

**Issue by sir-exasol** [exasol/virtual-schema-common-java#222] opened 2021-03-12 11:41 UTC
The column types of the generated sql is different to the types mentioned in the metadata for:
`HASHTYPE`, `GEOMETRY`, `TIMESTAMP WITH LOCAL TIME ZONE`, `INTERVAL`, `CHAR`.
The types are correct if `IS_LOCAL=TRUE` is given, because it generates `SELECT` without explicitly mentioned types instead of `IMPORT` statements.

| Type according to Metadata  | Actually generated type |
| ------------- | ------------- |
| HASHTYPE(n BYTE)  | CHAR(2*n) UTF8  |
| GEOMETRY(srid)  | VARCHAR(2000000) UTF8  |
| TIMESTAMP WITH LOCAL TIME ZONE | TIMESTAMP |
| INTERVAL YEAR TO MONTH | VARCHAR(9) UTF8 |
| INTERVAL DAY TO SECOND | VARCHAR(21) UTF8 |
| CHAR(n) ASCII | CHAR(n) UTF8 |
| VARCHAR(n) ASCII | VARCHAR(n) UTF8 |

This causes problems in the compiler, because we are refactoring our handling of data types. Please either change the reported metadata or the types in the generated sql to be consistent. Below is an example of how to reproduce this issue:

```sql
CREATE JAVA ADAPTER SCRIPT native.jdbc_adapter AS
    %scriptclass com.exasol.adapter.RequestDispatcher;
    %jvmoption -Xms64m -Xmx64m;
    %jar /buckets/testing/jdbc-adapter/virtualschema-jdbc-adapter.jar;
/
 
-- Replace PORT with the used port number:
CREATE CONNECTION vs_connection TO 'jdbc:exa:localhost:39256' USER 'sys' IDENTIFIED BY 'exasol';
 
CREATE VIRTUAL SCHEMA vs USING native.jdbc_adapter WITH
    CONNECTION_NAME='VS_CONNECTION'
    SCHEMA_NAME='NATIVE'
    IS_LOCAL='TRUE';
    
drop virtual schema vs_nonlocal cascade;
CREATE  VIRTUAL SCHEMA vs_nonlocal USING native.jdbc_adapter WITH
    CONNECTION_NAME='VS_CONNECTION'
    SCHEMA_NAME='NATIVE'
    IS_LOCAL='FALSE';

create table native.t_hash(a hashtype(1 byte));
create table native.t_geo(a geometry, b geometry(5));
create table native.t_timestamps(a timestamp, b timestamp with local time zone);
create table native.t_interval(a interval year (5) to month, b interval day (5) to second (5));
create table native.t_char(a char(10) ascii, b char(10) utf8, c varchar(10) ascii, d varchar(10) utf8);

ALTER VIRTUAL SCHEMA vs REFRESH;
ALTER VIRTUAL SCHEMA vs_nonlocal REFRESH;

EXPLAIN VIRTUAL SELECT a FROM vs.t_hash; -- correct
/* The following query returns:
IMPORT INTO (c1 CHAR(2) UTF8) FROM JDBC AT VS_CONNECTION STATEMENT 'SELECT "T_HASH"."A" FROM "NATIVE"."T_HASH"'
But the type should be HASHTYPE(1 BYTE) instead of CHAR(2).
The metadata correctly identifies the type of column a as HASHTYPE:
        "columns": [
          {
            "adapterNotes": "{\"jdbcDataType\":126,\"typeName\":\"HASHTYPE\"}",
            "dataType": {
              "bytesize": 1,
              "type": "HASHTYPE"
            },
            "name": "A"
          }
        ],
*/
EXPLAIN VIRTUAL SELECT a FROM vs_nonlocal.t_hash; -- 

/* The following queries also return sql with incorrect types */
EXPLAIN VIRTUAL SELECT a,b FROM vs_nonlocal.t_geo;
EXPLAIN VIRTUAL SELECT a,b FROM vs_nonlocal.t_timestamps;
EXPLAIN VIRTUAL SELECT a,b FROM vs_nonlocal.t_interval;
EXPLAIN VIRTUAL SELECT * FROM vs_nonlocal.t_char;

```

**Comment by AnastasiiaSergienko** [comment] 2021-03-17 09:59
Hi @sir-exasol 

Thanks for the scripts, I was able to reproduce the issue.

The data types are mapped in the 'wrong' way because our JDBC driver reports them in this way.
So this is what we get from our JDBC driver:

| Type according to Metadata  | Type reported by the JDBC driver |
| ------------- | ------------- |
| HASHTYPE(2 BYTE)  | JDBC Type: 1, Type name: CHAR, Size: 2  | 
| GEOMETRY(srid)  | JDBC Type: 12, Type name: VARCHAR, Size: 2000000  |
| TIMESTAMP WITH LOCAL TIME ZONE | JDBC Type: 93, Type name: TIMESTAMP |
| INTERVAL YEAR TO MONTH | JDBC Type: 12, Type name: INTERVAL YEAR TO MONTH, Size: 9 |
| INTERVAL DAY TO SECOND | JDBC Type: 12, Type name: INTERVAL DAY TO SECOND, Size: 12 |
| CHAR(10) UTF8 | JDBC Type: 1, Type name: CHAR, Size: 10 |
| CHAR(10) ASCII | JDBC Type: 1, Type name: CHAR, Size: 10 |
| VARCHAR(10) UTF8 | JDBC Type: 12, Type name: VARCHAR, Size: 10 |
| VARCHAR(10) ASCII | JDBC Type: 12, Type name: VARCHAR, Size: 10 |

So, HASHTYPE, GEOMETRY and TIMESTAMP WITH LOCAL TIME ZONE cannot be recognized from the information the JDBC driver provides.

For CHAR ASCII and VARCHAR(10) ASCII the driver doesn't report the octet length(size), it's always empty. So for UTF8 CHAR/VARCHAR and ASCII we always get the same information, it's not possible to distinguish between them. The driver should report the octet length, then our mapping will work correctly.

INTERVAL YEAR TO MONTH and  INTERVAL DAY TO SECOND could be theoretically identified by names, but we don't have precision information here, so it can be mapped incorrectly if we use default values.

So a clean solution here: add some switch to our JDBC driver that allows us to get 'pure Exasol' data types instead of common data types that are used in the driver. We won't fix this on our side, because it would break the way the Virtual Schemas implemented now.

We still can discuss mapping of INTERVAL YEAR TO MONTH and INTERVAL DAY TO SECOND, but this looks quite dangerous without reported precision.

**Comment by sir-exasol** [comment] 2021-03-17 12:20
Thanks for the information @AnastasiiaSergienko. Would it be possible to change the metadata instead? I.e. if the column type is going to be CHAR instead of HASHTYPE anyways, then the adapter should just say so in the metadata.

**Comment by AnastasiiaSergienko** [comment] 2021-03-17 14:17
I'm going to check if it's possible

**Comment by AnastasiiaSergienko** [comment] 2021-03-18 13:57
After a few discussions and tests we've created an idea ticket for improving the JDBC driver. The problem can't be fixed properly on the adapter side, I'm sorry @sir-exasol 

Here is the link to the ticket: https://www.exasol.com/support/browse/IDEA-613

I'm closing the ticket for now.

**Closed by AnastasiiaSergienko** 2021-03-18 13:57 UTC
Labels: bug, decision:wont-fix
